export const clientPairs = [
    "Reconosiendome",
    "CATSA",
    "Red Básica",
    "Steffanoni",
    "Integramente",
    "biancolatte",
    "Jumbo Studio Metalworks",
    "espaciointerior",
    "js",
    "Quinta Las Canteras",
    "Transportación B&B",
    "Platería Mexicana María de Lourdes",
    "Idea de Oriente",
    "MG Propeller",
    "Hix Adventure",
    "sidsen",
    "Grupo Darfi",
    "Bese Rent A Car",
    "One Production",
    "Ixtla",
    "ICA",
    "provaccines",
    "Tenaris Tamsa",
    "laescuadra"
];

export const clientPairsWeb = [
    "https://reconosiendome.mx/",
    "CATSA",
    "Red Básica",
    "http://steffanoni.com/",
    "http://integramente.mx/",
    "biancolatte",
    "Jumbo Studio Metalworks",
    "http://espacio-interior.com/",
    "https://jsjumbostudio.com/",
    "Quinta Las Canteras",
    "Transportación B&B",
    "Platería Mexicana María de Lourdes",
    "Idea de Oriente",
    "MG Propeller",
    "Hix Adventure",
    "sidsen",
    "Grupo Darfi",
    "Bese Rent A Car",
    "One Production",
    "Ixtla",
    "ICA",
    "https://provaccines.com/",
    "Tenaris Tamsa",
    "https://laescuadra.mx/"
];
